# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#0a100d"

# Main text color
theme[main_fg]="#fdfffd"

# Title color for boxes
theme[title]="#62e2a4"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#7dd6c8"

# Background color of selected item in processes box
theme[selected_bg]="#12221a"

# Foreground color of selected item in processes box
theme[selected_fg]="#62e2a4"

# Color of inactive/disabled text
theme[inactive_fg]="#3f5a4c"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#a8f0b3"

# Box outline and divider line color
theme[cpu_box]="#6fd48c"
theme[mem_box]="#6fd48c"
theme[net_box]="#6fd48c"
theme[proc_box]="#6fd48c"
theme[div_line]="#3f5a4c"

# Gradient for all meters and graphs
theme[temp_start]="#7dd6c8"
theme[temp_mid]="#62e2a4"
theme[temp_end]="#6fd48c"


theme[cpu_start]="#7dd6c8"
theme[cpu_mid]="#62e2a4"
theme[cpu_end]="#6fd48c"


theme[free_start]="#62e2a4"
theme[free_mid]="#6fd48c"
theme[free_end]="#a8f0b3"


theme[cached_start]="#b48cff"
theme[cached_mid]="#b48cff"
theme[cached_end]="#b48cff"


theme[available_start]="#7dd6c8"
theme[available_mid]="#7dd6c8"
theme[available_end]="#7dd6c8"


theme[used_start]="#62e2a4"
theme[used_mid]="#7d8cff"
theme[used_end]="#b48cff"


theme[download_start]="#b48cff"
theme[download_mid]="#7dd6c8"
theme[download_end]="#62e2a4"


theme[upload_start]="#b48cff"
theme[upload_mid]="#7dd6c8"
theme[upload_end]="#62e2a4"